// Generated by CoffeeScript 1.12.7
(function() {
  var BUTTON_HEIGHT_MAP, BUTTON_WIDTH_MAP, ButtonThemed, FONTSIZE_MAP, m, ref, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  ref = require('./CONSTANT'), BUTTON_WIDTH_MAP = ref.BUTTON_WIDTH_MAP, BUTTON_HEIGHT_MAP = ref.BUTTON_HEIGHT_MAP, FONTSIZE_MAP = ref.FONTSIZE_MAP;

  module.exports = ButtonThemed = (function() {
    function ButtonThemed(arg) {
      var ref1, ref2, ref3, ref4, ref5;
      this.label = arg.label, this.disabled = (ref1 = arg.disabled) != null ? ref1 : false, this.onClick = (ref2 = arg.onClick) != null ? ref2 : u.noOp, this.data = (ref3 = arg.data) != null ? ref3 : '', this.size = (ref4 = arg.size) != null ? ref4 : 'M', this.width = (ref5 = arg.width) != null ? ref5 : 'FIXED';
      this.onClickInternal = bind(this.onClickInternal, this);
    }

    ButtonThemed.prototype.onClickInternal = function(e) {
      var data;
      if (!this.disabled) {
        data = u.getCurrentTargetData(e, 'data');
        return this.onClick(data);
      }
    };

    ButtonThemed.prototype.view = function() {
      var self;
      self = this;
      return m("button.ButtonThemed", {
        style: {
          padding: this.width === 'PADDING' ? '0 16px' : 0,
          width: this.width === 'PADDING' ? 'auto' : this.width === 'FIXED' ? BUTTON_WIDTH_MAP[this.size] : this.width,
          height: BUTTON_HEIGHT_MAP[this.size],
          lineHeight: BUTTON_HEIGHT_MAP[this.size],
          fontSize: FONTSIZE_MAP[this.size]
        },
        onclick: this.onClickInternal,
        'data-data': this.data,
        disabled: this.disabled
      }, this.label);
    };

    return ButtonThemed;

  })();

  ButtonThemed.mss = {
    ButtonThemed: {
      position: 'relative',
      borderRadius: '4px',
      border: '1px solid #2F88FF',
      textAlign: 'center',
      color: '#FFF',
      background: '#2F88FF',
      cursor: 'pointer',
      $hover_$focus: {
        borderColor: '#57A5FF',
        background: '#57A5FF'
      },
      $disabled: {
        borderColor: '#A8D7FF',
        background: '#A8D7FF',
        cursor: 'not-allowed'
      },
      $focus: {
        outline: 'none'
      },
      $active: {
        borderColor: '#1C68D9',
        background: '#1C68D9'
      }
    }
  };

}).call(this);
