// Generated by CoffeeScript 2.0.2
(function() {
  var Button, m, s, style, u;

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  Button = class Button {
    constructor({
        text: text, // String
        prefix: prefix, // mithril svg view
        suffix: suffix, // mithril svg view
        data = null, // HashMap
        onClick = u.noOp // (HashMap) -> a
      }) {
      this.onClickInternal = this.onClickInternal.bind(this);
      this.text = text;
      this.prefix = prefix;
      this.suffix = suffix;
      this.onClick = onClick;
      this.dataJSON = JSON.stringify(data);
    }

    onClickInternal(e) {
      var data, json;
      json = u.getCurrentTargetData(e, 'json');
      data = JSON.parse(json);
      return this.onClick(data);
    }

    view() {
      var self;
      self = this;
      return m('.Button', {
        onclick: this.onClickInternal,
        'data-json': this.dataJSON
      }, m('.Prefix', this.prefix), m('span', this.text), m('.Suffix', this.suffix));
    }

  };

  Button.mss = {
    Button: s.LineSize('2em', '1em')({
      position: 'relative',
      width: '100px',
      textAlign: 'center',
      background: style.main[4],
      color: style.text[8],
      Prefix_Suffix: {
        position: 'absolute',
        svg: {
          fill: style.text[8],
          height: '1.4em',
          width: '1.4em'
        }
      },
      Prefix: {
        left: '0.3em',
        top: '0.3em'
      },
      Suffix: {
        right: '0.3em',
        top: '0.3em'
      },
      $hover: {
        cursor: 'pointer',
        background: style.main[5]
      }
    })
  };

  module.exports = Button;

}).call(this);
