// Generated by CoffeeScript 1.10.0
(function() {
  var Button, m, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  Button = (function() {
    function Button(arg) {
      var data, ref;
      this.text = arg.text, this.prefix = arg.prefix, this.suffix = arg.suffix, data = arg.data, this.onClick = (ref = arg.onClick) != null ? ref : (function() {});
      this.onClickInternal = bind(this.onClickInternal, this);
      this.dataJSON = typeof date !== "undefined" && date !== null ? JSON.stringify(data) : '';
    }

    Button.prototype.onClickInternal = function(e) {
      var data, json;
      json = u.getCurrentTargetData(e, 'json');
      data = json ? JSON.parse(json) : void 0;
      return this.onClick(data);
    };

    Button.prototype.view = function() {
      var self;
      self = this;
      return m('.Button', {
        onclick: this.onClickInternal,
        'data-json': this.dataJSON
      }, this.prefix, m('span', this.text), this.suffix);
    };

    return Button;

  })();

  Button.mss = {
    Button: s.LineSize('2em', '1em')({
      width: '100px',
      textAlign: 'center',
      background: style.main[4],
      color: style.text[8],
      $hover: {
        cursor: 'pointer',
        background: style.main[5]
      }
    })
  };

  module.exports = Button;

}).call(this);
