// Generated by CoffeeScript 2.3.0
(function() {
  var CheckBox, m, s, style, u;

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  CheckBox = class CheckBox {
    constructor({enable: enable = true, onToggle: onToggle = u.noOp}) { // Boolean // (Boolean) -> a
      this.onToggleInternal = this.onToggleInternal.bind(this);
      this.enable = enable;
      this.onToggle = onToggle;
    }

    onToggleInternal(e) {
      this.enable = !this.enable;
      return this.onToggle(this.enable);
    }

    view() {
      return m('.CheckBox', {
        onclick: this.onToggleInternal,
        className: this.enable ? 'Enabled' : 'Disabled'
      }, '✔');
    }

  };

  CheckBox.mss = {
    CheckBox: {
      display: 'inline-block',
      width: '1em',
      height: '1em',
      lineHeight: '1em',
      textAlign: 'center',
      cursor: 'pointer',
      border: '1px solid ' + style.main[4],
      color: style.main[4],
      borderRadius: '0.1em',
      verticalAlign: 'middle',
      userSelect: 'none',
      padding: '0.2em 0.1em 0 0.1em'
    },
    '.CheckBox.Enabled': {
      background: style.main[4],
      color: '#fff'
    },
    '.CheckBox.Disabled': {
      background: 'none',
      color: style.main[4]
    }
  };

  module.exports = CheckBox;

}).call(this);
