// Generated by CoffeeScript 1.12.7
(function() {
  var CheckBox, m, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  CheckBox = (function() {
    function CheckBox(arg) {
      var ref, ref1;
      this.enable = (ref = arg.enable) != null ? ref : true, this.onToggle = (ref1 = arg.onToggle) != null ? ref1 : u.noOp;
      this.onToggleInternal = bind(this.onToggleInternal, this);
    }

    CheckBox.prototype.onToggleInternal = function(e) {
      this.enable = !this.enable;
      return this.onToggle(this.enable);
    };

    CheckBox.prototype.view = function() {
      return m('.CheckBox', {
        onclick: this.onToggleInternal,
        className: this.enable ? 'Enabled' : 'Disabled'
      }, '✔');
    };

    return CheckBox;

  })();

  CheckBox.mss = {
    CheckBox: {
      display: 'inline-block',
      width: '1em',
      height: '1em',
      lineHeight: '1em',
      textAlign: 'center',
      cursor: 'pointer',
      border: '1px solid ' + style.main[4],
      color: style.main[4],
      borderRadius: '0.1em',
      verticalAlign: 'middle',
      userSelect: 'none',
      padding: '0.2em 0.1em 0 0.1em'
    },
    '.CheckBox.Enabled': {
      background: style.main[4],
      color: '#fff'
    },
    '.CheckBox.Disabled': {
      background: 'none',
      color: style.main[4]
    }
  };

  module.exports = CheckBox;

}).call(this);
