// Generated by CoffeeScript 1.12.7
(function() {
  var CHECK_SVG, CheckBox, HYPHEN_SVG, m, ref, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  ref = require('./CONSTANT'), CHECK_SVG = ref.CHECK_SVG, HYPHEN_SVG = ref.HYPHEN_SVG;

  CheckBox = (function() {
    function CheckBox(arg) {
      var ref1, ref2, ref3, ref4, ref5;
      this.selected = (ref1 = arg.selected) != null ? ref1 : true, this.label = (ref2 = arg.label) != null ? ref2 : 'foo', this.disabled = (ref3 = arg.disabled) != null ? ref3 : false, this.partial = (ref4 = arg.partial) != null ? ref4 : false, this.onToggle = (ref5 = arg.onToggle) != null ? ref5 : u.noOp;
      this.onToggleInternal = bind(this.onToggleInternal, this);
    }

    CheckBox.prototype.onToggleInternal = function(e) {
      this.selected = !this.selected;
      return this.onToggle(this.selected);
    };

    CheckBox.prototype.view = function() {
      return m('.CheckBox', {
        onclick: this.onToggleInternal,
        className: this.selected ? 'Enabled' : 'Disabled'
      }, this.enabled ? this.partial ? HYPHEN_SVG : CHECK_SVG : void 0);
    };

    return CheckBox;

  })();

  CheckBox.mss = {
    CheckBox: {
      display: 'inline-block',
      width: '1em',
      height: '1em',
      lineHeight: '1em',
      textAlign: 'center',
      cursor: 'pointer',
      border: '1px solid ' + style.main[4],
      color: style.main[4],
      borderRadius: '0.1em',
      verticalAlign: 'middle',
      userSelect: 'none',
      padding: 0,
      svg: {
        width: '1em',
        height: '1em'
      }
    },
    '.CheckBox.Enabled': {
      background: style.main[4],
      svg: {
        fill: '#fff'
      }
    },
    '.CheckBox.Disabled': {
      background: 'none',
      color: style.main[4],
      svg: {
        fill: style.main[4]
      }
    }
  };

  module.exports = CheckBox;

}).call(this);
