// Generated by CoffeeScript 2.3.0
(function() {
  var chn, eng;

  eng = {
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    dayName: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  };

  chn = {
    hour: '小时',
    minute: '分钟',
    second: '秒',
    dayName: ['一', '二', '三', '四', '五', '六', '七']
  };

  module.exports = chn;

}).call(this);
