// Generated by CoffeeScript 1.10.0
(function() {
  var Modal, m, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  style = require('./style');

  Modal = (function() {
    function Modal(arg) {
      var ref, ref1;
      this.widget = arg.widget, this.clickToHide = (ref = arg.clickToHide) != null ? ref : true, this.onHide = (ref1 = arg.onHide) != null ? ref1 : (function() {});
      this.hide = bind(this.hide, this);
      this.show = bind(this.show, this);
      this.onClickInternal = bind(this.onClickInternal, this);
      this.showWidget = false;
    }

    Modal.prototype.onClickInternal = function(e) {
      if (this.clickToHide && (u.targetHasClass(u.getTarget(e), 'Modal'))) {
        this.showWidget = false;
        return this.onHide();
      }
    };

    Modal.prototype.show = function() {
      return this.showWidget = true;
    };

    Modal.prototype.hide = function() {
      this.showWidget = false;
      return this.onHide();
    };

    Modal.prototype.view = function() {
      if (this.showWidget) {
        return m('.Modal', {
          onclick: this.onClickInternal
        }, m('.HVCenter', this.widget.view()));
      }
    };

    return Modal;

  })();

  Modal.mss = {
    Modal: {
      width: '100%',
      height: '100%',
      position: 'fixed',
      top: 0,
      left: 0,
      background: style.modalBG,
      zIndex: 9999,
      $before: {
        content: '""',
        display: 'inline-block',
        height: '100%',
        verticalAlign: 'middle'
      },
      HVCenter: {
        display: 'inline-block',
        width: '100%',
        textAlign: 'center',
        opacity: 1,
        verticalAlign: 'middle'
      }
    }
  };

  module.exports = Modal;

}).call(this);
