// Generated by CoffeeScript 1.12.7
(function() {
  var Modal, m, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  style = require('./style');

  Modal = (function() {
    function Modal(arg) {
      var ref, ref1, ref2;
      this.widget = arg.widget, this.clickToHide = (ref = arg.clickToHide) != null ? ref : true, this.escToHide = (ref1 = arg.escToHide) != null ? ref1 : true, this.onHide = (ref2 = arg.onHide) != null ? ref2 : u.noOp;
      this.hide = bind(this.hide, this);
      this.show = bind(this.show, this);
      this.onEscInternal = bind(this.onEscInternal, this);
      this.onClickInternal = bind(this.onClickInternal, this);
      this.showWidget = false;
    }

    Modal.prototype.onClickInternal = function(e) {
      var t;
      t = u.getTarget(e);
      if (this.clickToHide && ((u.targetHasClass(t, 'Modal')) || (u.targetHasClass(t, 'HVCenter')))) {
        return this.hide();
      }
    };

    Modal.prototype.onEscInternal = function(e) {
      if ((e.key === 'Escape' || e.keyCode === 27) && this.escToHide) {
        this.showWidget = false;
        m.redraw();
        return true;
      }
    };

    Modal.prototype.show = function() {
      return this.showWidget = true;
    };

    Modal.prototype.hide = function() {
      this.showWidget = false;
      return this.onHide();
    };

    Modal.prototype.view = function() {
      var self;
      self = this;
      if (this.showWidget) {
        return m('.Modal', {
          onclick: this.onClickInternal,
          oncreate: function() {
            return window.addEventListener('keyup', self.onEscInternal, true);
          },
          onremove: function() {
            return window.removeEventListener('keyup', self.onEscInternal, true);
          }
        }, m('.HVCenter', this.widget.view()));
      }
    };

    return Modal;

  })();

  Modal.mss = {
    Modal: {
      width: '100%',
      height: '100%',
      position: 'fixed',
      top: 0,
      left: 0,
      background: style.modalBG,
      zIndex: 9999,
      $before: {
        content: '""',
        display: 'inline-block',
        height: '100%',
        verticalAlign: 'middle'
      },
      HVCenter: {
        display: 'inline-block',
        width: '100%',
        textAlign: 'center',
        opacity: 1,
        verticalAlign: 'middle'
      }
    }
  };

  module.exports = Modal;

}).call(this);
