// Generated by CoffeeScript 2.3.0
(function() {
  var Notify, contentArray, dataArray, iconArray, keyCounter, m, s, style, timerArray, u;

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  style = require('./style');

  contentArray = [];

  iconArray = [];

  dataArray = [];

  timerArray = [];

  keyCounter = 0;

  Notify = class Notify {
    constructor({duration: duration = 3000, onClick: onClick = u.noOp}) { // Int // data -> a
      this.onClickInternal = this.onClickInternal.bind(this);
      this.show = this.show.bind(this);
      this.hideInternal = this.hideInternal.bind(this);
      this.duration = duration;
      this.onClick = onClick;
      this.indexArray = [];
    }

    onClickInternal(e) {
      var data, index;
      index = parseInt(u.getCurrentTargetData(e, 'index'));
      data = JSON.parse(u.getCurrentTargetData(e, 'data'));
      this.hideInternal(index);
      return this.onClick(data);
    }

    show(icon, content, data = null) {
      contentArray.push({
        content: content,
        context: this,
        key: keyCounter++
      });
      iconArray.push(icon);
      dataArray.push(data);
      return timerArray.push(setTimeout(() => {
        return this.hideInternal(0);
      }, this.duration));
    }

    hideInternal(i) {
      iconArray.splice(i, 1);
      contentArray.splice(i, 1);
      dataArray.splice(i, 1);
      clearTimeout(timerArray[i]);
      timerArray.splice(i, 1);
      return m.redraw();
    }

    view() {
      var content, context, i, key;
      return m('.Notify', (function() {
        var j, len, results;
        results = [];
        for (i = j = 0, len = contentArray.length; j < len; i = ++j) {
          ({key, content, context} = contentArray[i]);
          if (context === this) {
            results.push(m('.NotifyItem', {
              key: key,
              'data-index': i,
              'data-data': JSON.stringify(dataArray[i]),
              onclick: this.onClickInternal,
              style: {
                right: '1em',
                top: (1 + 5 * i) + 'em'
              }
            }, m('.Icon', iconArray[i]), m('.Content', content)));
          }
        }
        return results;
      }).call(this));
    }

  };

  Notify.mss = {
    Notify: {
      NotifyItem: {
        width: '20em',
        height: '4em', // if you change this, please change in the view too
        position: 'fixed',
        right: '1em',
        background: '#fff',
        border: '1px solid ' + style.border[4],
        zIndex: 9999,
        borderRadius: '0.4em',
        transition: 'top 0.1s ease',
        Content: {
          width: '16em',
          textAlign: 'center',
          display: 'inline-block',
          verticalAlign: 'middle'
        },
        Icon_CloseBtn: {
          width: '4em',
          textAlign: 'center',
          display: 'inline-block',
          svg: s.LineSize('4em', '1em')({
            verticalAlign: 'middle'
          })
        }
      }
    }
  };

  module.exports = Notify;

}).call(this);
