// Generated by CoffeeScript 1.12.7
(function() {
  var QuestionMark, helpIcon, m, s, style, u;

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  style = require('./style');

  helpIcon = require('mmsvg/google/msvg/action/help');

  QuestionMark = (function() {
    function QuestionMark(arg) {
      var ref, ref1;
      this.icon = (ref = arg.icon) != null ? ref : helpIcon, this.message = (ref1 = arg.message) != null ? ref1 : "hello world!";
    }

    QuestionMark.prototype.view = function() {
      return m('.QuestionMark', m('span', this.icon), m('.Message', m.trust(this.message)), m('.Arrow'), m('.ArrowBorder'));
    };

    return QuestionMark;

  })();

  QuestionMark.mss = {
    QuestionMark: {
      position: 'relative',
      display: 'inline-block',
      width: '2em',
      height: '2em',
      svg: {
        fill: style.main[4]
      },
      Message: {
        display: 'none',
        position: 'absolute',
        background: "#fff",
        border: '1px solid #d8e2f5',
        boxShadow: '0 0 5px #dee2f5',
        borderRadius: '2px',
        width: '400px',
        left: '-40px',
        bottom: '33px',
        padding: '8px'
      },
      Arrow: {
        display: 'none',
        position: 'absolute',
        top: '-13px',
        left: '5px',
        width: '11px',
        height: '11px',
        background: '#fff',
        zIndex: 1,
        transform: 'rotate(45deg)'
      },
      ArrowBorder: {
        display: 'none',
        position: 'absolute',
        top: '-14px',
        left: '4px',
        zIndex: -1,
        width: '12px',
        height: '12px',
        border: '1px solid #d8e2f5',
        boxShadow: '0 0 5px #dee2f5',
        transform: 'rotate(45deg)'
      },
      $hover: {
        Arrow_ArrowBorder_Message: {
          display: 'block'
        }
      }
    }
  };

  module.exports = QuestionMark;

}).call(this);
