// Generated by CoffeeScript 2.0.2
(function() {
  var cyan, green, grey, magenta, orange, red;

  grey = ["#292929", "#525252", "#7a7a7a", "#a3a3a3", "#cccccc", "#d6d6d6", "#e0e0e0", "#ebebeb", "#f5f5f5"];

  red = ['#2d0404', '#5a0808', '#860d0d', '#b31111', '#e01515', '#e64444', '#ec7373', '#f3a1a1', '#f9d0d0'];

  green = ['#132608', '#264c10', '#3a7219', '#4d9821', '#60be29', '#80cb54', '#a0d87f', '#bfe5a9', '#dff2d4'];

  magenta = ['#2f0720', '#5d0f3f', '#8c165f', '#ba1e7e', '#e9259e', '#ed51b1', '#f27cc5', '#f6a8d8', '#fbd3ec'];

  orange = ['#331300', '#662700', '#993a00', '#cc4e00', '#ff6100', '#ff8133', '#ffa066', '#ffc099', '#ffdfcc'];

  cyan = ['#00252a', '#004a54', '#01707e', '#0195a8', '#01bad2', '#34c8db', '#67d6e4', '#99e3ed', '#ccf1f6'];

  module.exports = {
    text: grey,
    main: cyan,
    border: grey,
    warn: orange,
    modalBG: 'rgba(0,0,0,0.2)',
    grey,
    red,
    green,
    magenta,
    orange,
    cyan
  };

}).call(this);
