// Generated by CoffeeScript 2.3.0
(function() {
  var Switch, m, s, style, u;

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  Switch = class Switch {
    constructor({enable: enable = true, onToggle: onToggle = u.noOp}) { // Boolean // (Boolean) -> a
      this.onToggleInternal = this.onToggleInternal.bind(this);
      this.enable = enable;
      this.onToggle = onToggle;
    }

    onToggleInternal(e) {
      this.enable = !this.enable;
      return this.onToggle(this.enable);
    }

    view() {
      return m('.Switch', {
        onclick: this.onToggleInternal,
        className: this.enable ? 'Enabled' : 'Disabled'
      }, m('.SwitchBtn'));
    }

  };

  Switch.mss = {
    '.Switch.Enabled': {
      width: '2em',
      height: '1em',
      borderRadius: '0.6em',
      padding: '0.1em',
      background: style.main[4]
    },
    '.Switch.Disabled': {
      width: '2em',
      height: '1em',
      borderRadius: '0.6em',
      padding: '0.1em',
      background: style.grey[4],
      $hover: {
        background: style.grey[5]
      },
      SwitchBtn: {
        left: '1em'
      }
    },
    Switch: {
      display: 'inline-block',
      position: 'relative',
      $hover: {
        background: style.main[5],
        cursor: 'pointer'
      },
      SwitchBtn: {
        position: 'relative',
        width: '1em',
        height: '1em',
        borderRadius: '0.5em',
        background: '#fff',
        left: 0,
        transition: 'left 0.1s ease'
      }
    }
  };

  module.exports = Switch;

}).call(this);
