// Generated by CoffeeScript 2.3.1
(function() {
  var m, s, style, tableView, u;

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  style = require('./style');

  tableView = function(colMap, rowArray, verticalHeader = false) {
    var d, i, k, v;
    if (verticalHeader) {
      return m('table.TableView', (function() {
        var results;
        results = [];
        for (k in colMap) {
          v = colMap[k];
          results.push(m('tr', m('th', v), (function() {
            var j, len, results1;
            results1 = [];
            for (i = j = 0, len = rowArray.length; j < len; i = ++j) {
              d = rowArray[i];
              results1.push(m('td', d[k] != null ? m.trust(d[k].toString()) : ''));
            }
            return results1;
          })()));
        }
        return results;
      })());
    } else {
      return m('table.TableView', m('thead', m('tr', (function() {
        var results;
        results = [];
        for (k in colMap) {
          v = colMap[k];
          results.push(m('th', v));
        }
        return results;
      })())), m('tbody', (function() {
        var j, len, results;
        results = [];
        for (i = j = 0, len = rowArray.length; j < len; i = ++j) {
          d = rowArray[i];
          results.push(m('tr', {
            key: i
          }, (function() {
            var results1;
            results1 = [];
            for (k in colMap) {
              results1.push(m('td', d[k] != null ? m.trust(d[k].toString()) : ''));
            }
            return results1;
          })()));
        }
        return results;
      })()));
    }
  };

  tableView.mss = {
    TableView: {
      width: '100%',
      margin: '14px 0',
      borderCollapse: 'collapse',
      th_td: {
        border: '1px solid' + style.border[4],
        padding: '4px',
        textAlign: 'center',
        color: style.text[1],
        a: {
          color: style.text[3]
        }
      },
      th: {
        backgroundColor: style.main[4],
        color: style.text[8],
        fontWeight: 'normal'
      },
      'tr:nth-child(even)': {
        backgroundColor: style.border[8]
      }
    }
  };

  module.exports = tableView;

}).call(this);
