// Generated by CoffeeScript 1.12.7
(function() {
  var TextArea, m, s, style, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  style = require('./style');

  u = require('./utils');

  TextArea = (function() {
    function TextArea(arg) {
      var ref, ref1, ref2, ref3, ref4, ref5, ref6;
      this.content = (ref = arg.content) != null ? ref : '', this.disabled = (ref1 = arg.disabled) != null ? ref1 : false, this.placeholder = (ref2 = arg.placeholder) != null ? ref2 : '', this.onChange = (ref3 = arg.onChange) != null ? ref3 : u.noOp, this.onKeyup = (ref4 = arg.onKeyup) != null ? ref4 : u.noOp, this.resize = (ref5 = arg.resize) != null ? ref5 : 'none', this.rows = (ref6 = arg.rows) != null ? ref6 : 5;
      this.onkeyupInternal = bind(this.onkeyupInternal, this);
      this.onChangeInternal = bind(this.onChangeInternal, this);
      this.validationMsg = '';
    }

    TextArea.prototype.submit = function() {
      if (this.validationMsg === '') {
        return this.content;
      } else {
        return new Error(this.validationMsg);
      }
    };

    TextArea.prototype.validateInternal = function(c) {};

    TextArea.prototype.onChangeInternal = function(e) {
      var c, err;
      c = (u.getTarget(e)).value;
      err = this.onChange(c);
      this.validationMsg = '';
      if (err instanceof Error) {
        this.validationMsg = err.message;
      }
      return this.content = c;
    };

    TextArea.prototype.onkeyupInternal = function(e) {
      var c, err;
      c = (u.getTarget(e)).value;
      this.content = c;
      err = this.onKeyup(c);
      this.validationMsg = '';
      if (err instanceof Error) {
        return this.validationMsg = err.message;
      }
    };

    TextArea.prototype.view = function() {
      return m('.TextArea', m('textarea.Input', {
        disabled: this.disabled,
        onchange: this.onChangeInternal,
        onkeyup: this.onkeyupInternal,
        value: this.content,
        placeholder: this.placeholder,
        rows: this.rows,
        style: {
          resize: this.resize
        }
      }), this.validationMsg !== '' ? m('.ValidationMsg', this.validationMsg) : void 0);
    };

    return TextArea;

  })();

  TextArea.mss = {
    TextArea: {
      position: 'relative',
      width: '400px',
      Input: {
        display: 'block',
        border: '1px solid ' + style.border[4],
        fontSize: '1em',
        padding: '0 0.4em',
        WebkitAppearance: 'none',
        borderRadius: 0,
        width: '100%'
      },
      ValidationMsg: s.LineSize('1.93em', '1em')({
        background: style.warn[5],
        color: style.text[8],
        position: 'absolute',
        bottom: 0,
        left: 0,
        textAlign: 'center',
        zIndex: 99,
        width: '100%'
      })
    }
  };

  module.exports = TextArea;

}).call(this);
