// Generated by CoffeeScript 1.10.0
(function() {
  var cancelBubble, clearDateHMS, formatDate, formatDateWithHMS, formatXX, getCurrentTargetData, getTarget, getTargetData, parseDateWithHMS, targetHasClass;

  getTarget = function(event) {
    var elem;
    return elem = event.target || event.srcElement;
  };

  getTargetData = function(event, dataStr) {
    var elem;
    elem = event.target || event.srcElement;
    if (elem.dataset != null) {
      return elem.dataset[dataStr];
    } else {
      return elem.getAttribute('data-' + dataStr);
    }
  };

  getCurrentTargetData = function(event, dataStr) {
    var elem;
    elem = event.currentTarget;
    if (elem.dataset != null) {
      return elem.dataset[dataStr];
    } else {
      return elem.getAttribute('data-' + dataStr);
    }
  };

  targetHasClass = function(elem, str) {
    return (elem.className.indexOf(str)) !== -1;
  };

  cancelBubble = function(e) {
    if (e.cancelBubble === false) {
      e.cancelBubble = true;
    }
    if (typeof e.stopPropagation === "function") {
      e.stopPropagation();
    }
    return false;
  };

  clearDateHMS = function(date) {
    date.setHours(0);
    date.setMinutes(0);
    date.setSeconds(0);
    return date;
  };

  formatDate = function(date) {
    var dd, mm, yyyy;
    yyyy = date.getFullYear();
    mm = date.getMonth() + 1;
    dd = date.getDate();
    return yyyy + '-' + (formatXX(mm)) + '-' + (formatXX(dd));
  };

  formatDateWithHMS = function(date) {
    var hh, mm, ss;
    hh = date.getHours();
    mm = date.getMinutes();
    ss = date.getSeconds();
    return (formatDate(date)) + ' ' + (formatXX(hh)) + ':' + (formatXX(mm)) + ':' + (formatXX(ss));
  };

  parseDateWithHMS = function(dateString) {
    var date, dateStr, hh, mm, ref, ref1, ss, timeStr;
    ref = dateString.split(' '), dateStr = ref[0], timeStr = ref[1];
    date = new Date(dateStr);
    if (timeStr != null) {
      ref1 = timeStr.split(':'), hh = ref1[0], mm = ref1[1], ss = ref1[2];
      date.setHours(parseInt(hh));
      date.setMinutes(parseInt(mm));
      date.setSeconds(parseInt(ss));
    }
    return date;
  };

  formatXX = function(x) {
    if (x < 10) {
      return '0' + x.toString();
    } else {
      return x.toString();
    }
  };

  module.exports = {
    getTarget: getTarget,
    getTargetData: getTargetData,
    getCurrentTargetData: getCurrentTargetData,
    targetHasClass: targetHasClass,
    cancelEvent: cancelEvent,
    clearDateHMS: clearDateHMS,
    formatXX: formatXX,
    formatDate: formatDate,
    formatDateWithHMS: formatDateWithHMS,
    parseDateWithHMS: parseDateWithHMS,
    Switch: Switch
  };

}).call(this);
