// Generated by CoffeeScript 2.3.1
(function() {
  var cancelBubble, clearDateHMS, debounce, firstErrorInArray, formatDate, formatDateWithHMS, formatHMS, formatXX, getCurrentTargetData, getTarget, getTargetData, m, parseDateWithHMS, removeFromArray, spinner, svg, svgCounter, targetHasClass;

  m = require('mithril');

  // get event's target
  getTarget = function(event) {
    var elem;
    return elem = event.target || event.srcElement;
  };

  // get even's target's data-xxx
  getTargetData = function(event, dataStr) {
    var elem;
    elem = event.target || event.srcElement;
    if (elem.dataset != null) {
      return elem.dataset[dataStr];
    } else {
      return elem.getAttribute('data-' + dataStr);
    }
  };

  // get even's current target's data-xxx
  getCurrentTargetData = function(event, dataStr) {
    var elem;
    elem = event.currentTarget;
    if (elem.dataset != null) {
      return elem.dataset[dataStr];
    } else {
      return elem.getAttribute('data-' + dataStr);
    }
  };

  targetHasClass = function(elem, str) {
    return (elem.className.indexOf(str)) !== -1;
  };

  // cancelBubble
  cancelBubble = function(e) {
    // for IE
    if (e.cancelBubble === false) {
      e.cancelBubble = true;
    }
    if (typeof e.stopPropagation === "function") {
      e.stopPropagation();
    }
    return false;
  };

  // clear Date's hour minute and second
  clearDateHMS = function(date) {
    date.setHours(0);
    date.setMinutes(0);
    date.setSeconds(0);
    return date;
  };

  // format Date to yyyy-mm-dd
  formatDate = function(date) {
    var dd, mm, yyyy;
    yyyy = date.getFullYear();
    mm = date.getMonth() + 1;
    dd = date.getDate();
    return yyyy + '-' + (formatXX(mm)) + '-' + (formatXX(dd));
  };

  // format Date to yyyy-mm-dd
  formatHMS = function(date) {
    var hh, mm, ss;
    hh = date.getHours();
    mm = date.getMinutes();
    ss = date.getSeconds();
    return (formatXX(hh)) + ':' + (formatXX(mm)) + ':' + (formatXX(ss));
  };

  // format Date to yyyy-mm-dd hh:mm:ss
  formatDateWithHMS = function(date) {
    var hh, mm, ss;
    hh = date.getHours();
    mm = date.getMinutes();
    ss = date.getSeconds();
    return (formatDate(date)) + ' ' + (formatHMS(date));
  };

  // parse yyyy-mm-dd hh:mm:ss
  // parse yyyy-mm-dd
  parseDateWithHMS = function(dateString) {
    var date, dateStr, hh, mm, ss, timeStr;
    [dateStr, timeStr] = dateString.split(' ');
    date = new Date(dateStr);
    if (timeStr != null) {
      [hh, mm, ss] = timeStr.split(':');
      date.setHours(parseInt(hh));
      date.setMinutes(parseInt(mm));
      date.setSeconds(parseInt(ss));
    }
    return date;
  };

  // helper to format number to 2 digit
  formatXX = function(x) {
    if (x < 10) {
      return '0' + x.toString();
    } else {
      return x.toString();
    }
  };

  // find first Error in Array
  firstErrorInArray = function(arr) {
    var j, len, x;
    for (j = 0, len = arr.length; j < len; j++) {
      x = arr[j];
      if (x instanceof Error) {
        return x;
      }
    }
  };

  // remove an element from array and return it, return undefined if not in array
  removeFromArray = function(arr, x) {
    var i;
    i = arr.indexOf(x);
    if (i !== -1) {
      arr.splice(i, 1);
    }
    return void 0;
  };

  svgCounter = 0;

  svg = function(svg) {
    return m('i', {
      key: svgCounter++
    }, svg);
  };

  spinner = function(color, size = '2em', interval = '1s') {
    return svg(m.trust(`<svg version="1.1"\n    xmlns="http://www.w3.org/2000/svg"\n    xmlns:xlink="http://www.w3.org/1999/xlink"\n    x="0px"\n    y="0px"\n    width="${size}"\n    viewBox="0 0 80 80"\n    xml:space="preserve">\n    <path\n        fill="${color}"\n        d="M40,72C22.4,72,8,57.6,8,40C8,22.4,\n        22.4,8,40,8c17.6,0,32,14.4,32,32c0,1.1-0.9,2-2,2\n        s-2-0.9-2-2c0-15.4-12.6-28-28-28S12,24.6,12,40s12.6,\n        28,28,28c1.1,0,2,0.9,2,2S41.1,72,40,72z"\n        <!-- ANIMATION START -->\n        <animateTransform\n            attributeType="xml"\n            attributeName="transform"\n            type="rotate"\n            from="0 40 40"\n            to="360 40 40"\n            dur="${interval}"\n            repeatCount="indefinite"\n        />\n    </path>\n</svg>`));
  };

  debounce = function(fn, delay, leading = false) {
    var args, pending;
    pending = false;
    if (leading) {
      return function() {
        if (!pending) {
          fn.apply(this, arguments);
          pending = true;
          return setTimeout((function() {
            return pending = false;
          }), delay);
        }
      };
    } else {
      args = void 0;
      return function() {
        var self;
        args = arguments;
        self = this;
        if (!pending) {
          pending = true;
          return setTimeout(function() {
            pending = false;
            return fn.apply(self, args);
          }, delay);
        }
      };
    }
  };

  module.exports = {
    getTarget,
    getTargetData,
    getCurrentTargetData,
    targetHasClass,
    cancelBubble,
    clearDateHMS,
    formatXX,
    formatDate,
    formatHMS,
    formatDateWithHMS,
    parseDateWithHMS,
    firstErrorInArray,
    removeFromArray,
    noOp: (function() {}),
    svg,
    spinner,
    debounce
  };

}).call(this);
